namespace ADSDriver.Models.Entities
{
    public partial class MasterSuppliersParts
    {
      public virtual string ID {get; set;}
      public virtual string CODE {get; set;}
      public virtual string PARTNO {get; set;}
      public virtual string DESCR2 {get; set;}
      public virtual string OURPART {get; set;}
      public virtual string ALCOSTNT {get; set;}
      public virtual string ALSELLNT {get; set;}
      public virtual string ALSUPLIER {get; set;}
      public virtual string ALIAS {get; set;}
      public virtual string ALSELLQLD {get; set;}
      public virtual string ALIASDESC {get; set;}
      public virtual string ALCOSTQLD {get; set;}
      public virtual string DISGROUP {get; set;}
      public virtual string GROUPDESC {get; set;}
      public virtual string MULGROUP {get; set;}
      public virtual string MULGDES {get; set;}
      public virtual string USEMUL {get; set;}
      public virtual string SUPLIST {get; set;}
      public virtual string LCPTE {get; set;}
      public virtual string TAXINC {get; set;}
      public virtual string NETCOST {get; set;}
      public virtual string LPPER {get; set;}
      public virtual string TLC {get; set;}
      public virtual string LEADTIME {get; set;}
      public virtual string BARCODE {get; set;}
      public virtual string WEIGHT {get; set;}
      public virtual string VOLUME {get; set;}
      public virtual string PACKQTY {get; set;}
      public virtual string OUTER {get; set;}
      public virtual string UMEASURE {get; set;}
      public virtual string MULABS {get; set;}
      public virtual string ABSD {get; set;} 
      public virtual string MULCNS {get; set;}
      public virtual string CNSD {get; set;}
      public virtual string AWD {get; set;}
      public virtual string QWD {get; set;}
      public virtual string AUTOCSTABS {get; set;}
      public virtual string AUTOCSTCNS {get; set;}
      public virtual string COSTPMABS {get; set;}
      public virtual string ISMANCABS {get; set;}
      public virtual string COSTPMCNS {get; set;}
      public virtual string ISMANCCNS {get; set;}
      public virtual string AUTOSABS {get; set;}
      public virtual string AUTOSCNS {get; set;}
      public virtual string LASTUPDATE {get; set;}
      public virtual string SALEPMABS {get; set;}
      public virtual string ISMANSABS {get; set;}
      public virtual string SALEPMCNS { get; set; }
      public virtual string ISMANSCNS {get; set;}
      public virtual string WHOLEABS {get; set;}
      public virtual string LASTUPTIME {get; set;}
      public virtual string WHOLECNS {get; set;}
      public virtual string OLDPART {get; set;}
      public virtual string BARCODE2 {get; set;}
      public virtual string ALIASCODE {get; set;}
      public virtual string STDQB1 {get; set;}
      public virtual string STDQB2 {get; set;}
      public virtual string STDQBDISC1 {get; set;}
      public virtual string STDQBDISC2 {get; set;}
      public virtual string STDQBCST1 {get; set;}
      public virtual string STDQBCST2 {get; set;}
      public virtual string CODE9000 {get; set;}
      public virtual string NAME {get; set;}
      public virtual string ACTIVE {get; set;}
      public virtual string SUPPRODGRP {get; set;}
      public virtual string CPACKQTY {get; set;}
      public virtual string CATNAME {get; set;}
      public virtual string SPECIALON {get; set;}
      public virtual string SPECIALOFF {get; set;}
      public virtual string CATCOST {get; set;}
      public virtual string CATSELL {get; set;}
      public virtual string CATQB1 {get; set;}
      public virtual string CATQBCST1 {get; set;}
      public virtual string CATQB2 {get; set;}
      public virtual string CATQBCST2 {get; set;}
      public virtual string ACTIVECAT {get; set;}
      public virtual string CATCODE {get; set;}
      public virtual string DAYPRIOR {get; set;}
      public virtual string DAYEND {get; set;}
      public virtual string MINORDER {get; set;}
      public virtual string CATPER {get; set;}
      public virtual string SCATCODE {get; set;}
      public virtual string SCATNAME {get; set;}
      public virtual string SSPECIALON {get; set;}
      public virtual string SSPECIALOF {get; set;}
      public virtual string SDAYPRIOR {get; set;}
      public virtual string SDAYEND {get; set;}
      public virtual string SCATCOST {get; set;}
      public virtual string SCATSELL {get; set;}
      public virtual string SCPACKQTY {get; set;}
      public virtual string SMINORDER {get; set;}
      public virtual string SCATPER {get; set;}
      public virtual string SCATQB1 {get; set;}
      public virtual string SCATQBCST1 {get; set;}
      public virtual string SCATQB2 {get; set;}
      public virtual string SCATQBCST2 {get; set;}
      public virtual string AUXNOTE {get; set;}
    }
}
